SELECT
    DISTINCT(CAR_1.CAR_ID)
FROM
    CAR_RENTAL_COMPANY_CAR AS CAR_1
INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CARR
ON
    CAR_1.CAR_ID = CARR.CAR_ID
WHERE
    CAR_1.CAR_TYPE = '세단'
AND
    CARR.START_DATE LIKE '%-10-%'
ORDER BY
    CAR_1.CAR_ID DESC